name: Fund Portfolio Weekly Analysis

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:
    inputs:
      name:
        description: 'trigger'
        required: false
        default: 'manual'

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Test
        run: echo "workflow_dispatch is recognized!"
